# Generated by Django 5.0.2 on 2026-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_legacyuser_profile_telegramverification_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverification',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='telegramverification',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
