# Generated by Django 6.0.2 on 2026-02-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('break_duration', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('paused', 'Paused')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='users.user')),
            ],
        ),
    ]
