# Generated by Django 5.2.8 on 2026-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_alter_pomodorosession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='running', max_length=10),
        ),
    ]
